version: "3"

services:
  app: 
    build: .
    command: yarn start
    ports: 
      - "3000:3000"
    volumes: 
      - .:/user/app
  
  #Postgres Service
  db:
    image: postgres:12.7-alpine
    container_name: velma_db
    restart: always
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: buscas_db
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    networks:
      - velma_net

  pgadmin:
    container_name: pgadmin_velma
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.dev}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
        - pgadmin-velma:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - velma_net
    restart: always

networks:
  velma_net:
    driver: bridge

# Volumes
volumes:
  postgres-data:
    driver: local
  pgadmin-velma:
    driver: local